sudo: false
language: node_js
node_js:
- '10.0.0'
stages:
- test
jobs:
  include:
  - stage: test
    name: "Lint and Test"
    script:
    - yarn lint
    - yarn test
notifications:
  webhooks:
    secure: "fmT7I8UXZGMvU5gWLAzSp1fmjDL2ksgjK6pa+NHgjt29hlwSYNIBQN6e5CMb+KBaIyWi1Y9ZZCnio6kQwJHD/DDUBRYq/G0rKFV0tqEcvf8VBBbPnUQ5QDvcP2PFTY3F3TztWturab8CKKuwKRcgiBXIrpDhDsSb3qEmFhIy3VL50dPLosO+esWD1H5vmUR6zrXbYzthc9F4y6h+ELz4Fuy8P0XnjsFo9QtQepmb/KKZg847nuvMhq1rwFiynJk51ORuR0HkHTjdPAQY8jAsZpe1mb1alA6SOMTMg6G3nbyEvE+MlK6zvCrqp+SfVAwZX67IBphiA2B28W8uPZaTYIg+DgfxNHL7G6VPMUvXNZneXSsykWMnkuaghpi7k9vGfOxVbmh15AQAGkcZIVqby8Q6J+i9LK3xJND/7JvSL1UmepH012T7Ix7woyVm5VTizbUTkI1BOoPPRF5+LDx8w1Z0WGeAwj+C/oMhiQr2SCmJp7ozSSOyKRzQgTZOmGtcsTK27RILrE8cW5zQFojnXUeNuYW4gTqSOyNhBobdoyCNUZkk7h7WzTS2QzsNmByb4g8y1LI1td3rHO+viN2RNyw4bXm9e0j1CsYnHOMX5gz/o7uMP3FB4YU9vgwaOO9ykYlpzEYRXnDQnjbPdHyfCGOY6dfBMZX5OJ4+8PTfe8E="
